# Generated by Django 5.1.7 on 2025-06-23 20:14

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='college', chained_model_field='college', default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='stage',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='section', chained_model_field='section', default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stage', chained_model_field='stage', on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
