# Generated by Django 5.1.7 on 2026-05-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_college_chapter_section_chapter_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
    ]
